artifact_location: file:///K:/ETL_pipeline/%20Real-Time%20Sales%20Analytics%20Pipeline/sales-pipeline/mlruns/0
creation_time: 1779695574922
experiment_id: '0'
last_update_time: 1779695574922
lifecycle_stage: active
name: Default
